fullnameOverride: hive-metastore

metastore:
  replicas: 1

  image: k2sebeom/hive-postgres:4.0.0
  imagePullSecret: ""

  schema:
    init: true
    dbType: postgres

  config: |
    <configuration>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://localhost:5432/hivemetastore</value>
        <description>JDBC connect string for a JDBC metastore</description>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
        <description>Driver class name for a JDBC metastore</description>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>hive</value>
        <description>Username to use against metastore database</description>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value></value>
        <description>Password to use against metastore database</description>
    </property>
    </configuration>
