postgresql:
  auth:
    username: hive
    database: hivemetastore
    existingSecret: postgres-auth
    secretKeys:
      adminPasswordKey: ADMIN_PASSWORD
      userPasswordKey: USER_PASSWORD

  primary:
    persistence:
      enabled: false

  readReplicas:
    persistence:
      enabled: false

  volumePermissions:
    enabled: true
