{{- if .Values.metastore.schema.init }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.fullnameOverride }}-initschema
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.metastore.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.metastore.imagePullSecret }}
      {{- end }}
      containers:
        - name: init-schema
          image: {{ .Values.metastore.image }}
          command: [
            "/opt/hive/bin/schematool", "--verbose", "-initSchema", "-dbType", {{ .Values.metastore.schema.dbType }}
          ]
          volumeMounts:
            - name: hive-cfg
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
      volumes:
        - name: hive-cfg
          configMap:
            name: {{ .Values.fullnameOverride }}-config
{{- end }}
