apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.fullnameOverride }}
spec:
  type: ClusterIP
  ports:
    - port: 9083
      protocol: TCP
      targetPort: 9083
  selector:
    app: {{ .Values.fullnameOverride }}
  sessionAffinity: None
